/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminLayout: typeof import('./src/components/layouts/AdminLayout.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    GameTable: typeof import('./src/components/GameTable.vue')['default']
    GuessInput: typeof import('./src/components/GuessInput.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    QBadge: typeof import('quasar')['QBadge']
    QBanner: typeof import('quasar')['QBanner']
    QBtn: typeof import('quasar')['QBtn']
    QCard: typeof import('quasar')['QCard']
    QCardActions: typeof import('quasar')['QCardActions']
    QCardSection: typeof import('quasar')['QCardSection']
    QDialog: typeof import('quasar')['QDialog']
    QDrawer: typeof import('quasar')['QDrawer']
    QForm: typeof import('quasar')['QForm']
    QHeader: typeof import('quasar')['QHeader']
    QIcon: typeof import('quasar')['QIcon']
    QInput: typeof import('quasar')['QInput']
    QItem: typeof import('quasar')['QItem']
    QItemLabel: typeof import('quasar')['QItemLabel']
    QItemSection: typeof import('quasar')['QItemSection']
    QLayout: typeof import('quasar')['QLayout']
    QList: typeof import('quasar')['QList']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QRadio: typeof import('quasar')['QRadio']
    QSelect: typeof import('quasar')['QSelect']
    QSeparator: typeof import('quasar')['QSeparator']
    QSpace: typeof import('quasar')['QSpace']
    QTable: typeof import('quasar')['QTable']
    QTd: typeof import('quasar')['QTd']
    QToolbar: typeof import('quasar')['QToolbar']
    QToolbarTitle: typeof import('quasar')['QToolbarTitle']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsModal: typeof import('./src/components/StatsModal.vue')['default']
  }
}
