/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Footer: typeof import('./src/components/Footer.vue')['default']
    GameTable: typeof import('./src/components/GameTable.vue')['default']
    GuessInput: typeof import('./src/components/GuessInput.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    HelpModal: typeof import('./src/components/HelpModal.vue')['default']
    QBanner: typeof import('quasar')['QBanner']
    QBtn: typeof import('quasar')['QBtn']
    QForm: typeof import('quasar')['QForm']
    QInput: typeof import('quasar')['QInput']
    QLayout: typeof import('quasar')['QLayout']
    QPage: typeof import('quasar')['QPage']
    QPageContainer: typeof import('quasar')['QPageContainer']
    QSeparator: typeof import('quasar')['QSeparator']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsModal: typeof import('./src/components/StatsModal.vue')['default']
  }
}
